import express from "express";
import authRoutes from "../modules/auth/auth.routes.js";
import userRoutes from "../modules/users/user.routes.js";
import studentRoutes from "../modules/students/student.routes.js";
import companyRoutes from "../modules/companies/company.routes.js";
import opportunityRoutes from "../modules/opportunities/opportunity.routes.js";
import internshipRoutes from "../modules/internships/internship.routes.js";
import reportRoutes from "../modules/reports/report.routes.js";
import parameterRoutes from "../modules/parameters/parameter.routes.js";
import documentRoutes from "../modules/documents/document.routes.js";
import rolesRoutes from "../modules/roles/roles.routes.js";
import userAdministrativoRoutes from '../modules/usersAdministrativos/userAdministrativo.routes.js';
import sucursalRoutes from '../modules/sucursales/sucursal.routes.js';
import postulantRoutes from '../modules/postulants/routes/postulant.routes.js';
import postulantLogRoutes from '../modules/postulants/routes/postulantLogs.routes.js';
import locationRoutes from '../modules/shared/location/location.routes.js';
import programAllRoutes from '../modules/shared/programAll/programAll.routes.js';
import skillRoutes from '../modules/shared/skill/skill.routes.js';
import facultyRoutes from '../modules/faculty/faculty.routes.js';
import programRoutes from '../modules/program/program.routes.js';
import programFacultyRoutes from '../modules/program/programFaculty.routes.js';
import periodoRoutes from '../modules/periodos/periodo.routes.js';

const router = express.Router();

router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/students", studentRoutes);
router.use("/companies", companyRoutes);
router.use("/opportunities", opportunityRoutes);
router.use("/internships", internshipRoutes);
router.use("/reports", reportRoutes);
router.use("/parameters", parameterRoutes);
router.use("/documents", documentRoutes);
router.use("/roles", rolesRoutes);
router.use("/users-administrativos", userAdministrativoRoutes);
router.use("/sucursales", sucursalRoutes);
router.use("/postulants", postulantRoutes);
router.use("/postulant-logs", postulantLogRoutes);
router.use("/locations", locationRoutes);
router.use("/program-alls", programAllRoutes);
router.use("/skills", skillRoutes);
router.use("/faculties", facultyRoutes);
router.use("/programs", programRoutes);
router.use("/program-faculties", programFacultyRoutes);
router.use("/periodos", periodoRoutes);

export default router;
