import express from "express";
import authRoutes from "../modules/auth/auth.routes.js";
import userRoutes from "../modules/users/user.routes.js";
import studentRoutes from "../modules/students/student.routes.js";
import companyRoutes from "../modules/companies/company.routes.js";
import opportunityRoutes from "../modules/opportunities/opportunity.routes.js";
import internshipRoutes from "../modules/internships/internship.routes.js";
import reportRoutes from "../modules/reports/report.routes.js";
import parameterRoutes from "../modules/parameters/parameter.routes.js";
import documentRoutes from "../modules/documents/document.routes.js";
import rolesRoutes from "../modules/roles/roles.routes.js";
import userAdministrativoRoutes from '../modules/usersAdministrativos/userAdministrativo.routes.js';
import sucursalRoutes from '../modules/sucursales/sucursal.routes.js';
import postulantRoutes from '../modules/postulants/routes/postulant.routes.js';
import postulantLogRoutes from '../modules/postulants/routes/postulantLogs.routes.js';
import locationRoutes from '../modules/shared/location/location.routes.js';
import programAllRoutes from '../modules/shared/programAll/programAll.routes.js';
import skillRoutes from '../modules/shared/skill/skill.routes.js';
import facultyRoutes from '../modules/faculty/faculty.routes.js';
import programRoutes from '../modules/program/program.routes.js';
import programFacultyRoutes from '../modules/program/programFaculty.routes.js';
import periodoRoutes from '../modules/periodos/periodo.routes.js';
import dashboardRoutes from '../modules/dashboard/dashboard.routes.js';
import asignaturaRoutes from '../modules/asignaturas/asignatura.routes.js';
import oportunidadesMTMRoutes from '../modules/oportunidadesMTM/oportunidadMTM.routes.js';
import condicionCurricularRoutes from '../modules/condicionesCurriculares/condicionCurricular.routes.js';
import documentParametrizationRoutes from '../modules/parametrizacionDocumentos/documentParametrization.routes.js';
import documentPracticeDefinitionRoutes from '../modules/documentPracticeDefinition/documentPracticeDefinition.routes.js';
import documentMonitoringDefinitionRoutes from '../modules/documentMonitoringDefinition/documentMonitoringDefinition.routes.js';
import userSucursalRoutes from '../modules/userSucursal/userSucursal.routes.js';
import estudiantesHabilitadosRoutes from '../modules/estudiantesHabilitados/estudianteHabilitado.routes.js';
import legalizacionPracticaRoutes from '../modules/legalizacionPractica/legalizacionPractica.routes.js';
import acuerdoVinculacionPracticaPublicRoutes from '../modules/legalizacionPractica/acuerdoVinculacionPractica.public.routes.js';
import certificacionPracticaRoutes from '../modules/certificacionPractica/certificacionPractica.routes.js';
import certificacionPracticaPublicRoutes from '../modules/certificacionPractica/certificacionPractica.public.routes.js';
// Notificación: rutas directas desde cada módulo (sin archivo agregador)
import eventosRoutes from '../modules/notificacion/eventos/evento.routes.js';
import plantillasNotificacionRoutes from '../modules/notificacion/plantillasNotificacion/plantillaNotificacion.routes.js';
import variablesNotificacionRoutes from '../modules/notificacion/variablesNotificacion/variableNotificacion.routes.js';
import destinatariosNotificacionRoutes from '../modules/notificacion/destinatariosNotificacion/destinatarioNotificacion.routes.js';
import accessRoutes from '../modules/access/presentation/routes/access.routes.js';
import catalogRoutes from '../modules/catalogs/catalog.routes.js';
import reportingFiltersRoutes from '../modules/reportingFilters/reportingFilters.routes.js';

const router = express.Router();

router.use("/auth", authRoutes);
router.use("/access", accessRoutes);
router.use("/users", userRoutes);
router.use("/students", studentRoutes);
router.use("/companies", companyRoutes);
router.use("/opportunities", opportunityRoutes);
router.use("/internships", internshipRoutes);
router.use("/reports", reportRoutes);
router.use("/catalogs", catalogRoutes);
router.use("/reporting-filters", reportingFiltersRoutes);
router.use("/parameters", parameterRoutes);
router.use("/documents", documentRoutes);
router.use("/roles", rolesRoutes);
router.use("/users-administrativos", userAdministrativoRoutes);
router.use("/sucursales", sucursalRoutes);
router.use("/postulants", postulantRoutes);
router.use("/postulant-logs", postulantLogRoutes);
router.use("/locations", locationRoutes);
router.use("/program-alls", programAllRoutes);
router.use("/skills", skillRoutes);
router.use("/faculties", facultyRoutes);
router.use("/programs", programRoutes);
router.use("/program-faculties", programFacultyRoutes);
router.use("/periodos", periodoRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/asignaturas", asignaturaRoutes);
router.use("/oportunidades-mtm", oportunidadesMTMRoutes);
router.use("/condiciones-curriculares", condicionCurricularRoutes);
router.use("/parametrizacion-documentos", documentParametrizationRoutes);
router.use("/document-practice-definitions", documentPracticeDefinitionRoutes);
router.use("/document-monitoring-definitions", documentMonitoringDefinitionRoutes);
router.use("/user-sucursales", userSucursalRoutes);
router.use("/estudiantes-habilitados", estudiantesHabilitadosRoutes);
router.use("/acuerdos-vinculacion-practica", acuerdoVinculacionPracticaPublicRoutes);
router.use("/legalizaciones-practica", legalizacionPracticaRoutes);
router.use("/certificaciones-practica", certificacionPracticaRoutes);
router.use("/certificacion-practica-public", certificacionPracticaPublicRoutes);
// Notificación: cada submódulo montado bajo /notificacion y en URLs legacy
router.use("/notificacion/eventos", eventosRoutes);
router.use("/notificacion/plantillas", plantillasNotificacionRoutes);
router.use("/notificacion/variables", variablesNotificacionRoutes);
router.use("/notificacion/destinatarios", destinatariosNotificacionRoutes);
router.use("/parametros-plantilla", eventosRoutes);
router.use("/plantillas-notificacion", plantillasNotificacionRoutes);
router.use("/notification-variables", variablesNotificacionRoutes);
router.use("/destinatarios-notificacion", destinatariosNotificacionRoutes);

export default router;
