import mongoose from "mongoose";
/** profile_program_extra_info. tenant-1.sql. enrolled_program_id -> ProfileEnrolledProgram */
const schema = new mongoose.Schema({
  enrolledProgramId: { type: mongoose.Schema.Types.ObjectId, ref: "ProfileEnrolledProgram", required: true, index: true },
  mysqlId: { type: Number, unique: true, sparse: true },
  accordingCreditSemester: Number,
  enrolled: { type: Boolean, default: false },
  approvedCourses: String,
  currentCourses: String,
  approvedCredits: String,
  canPractice: { type: Boolean, default: false },
  cumulativeAverage: Number,
  disciplinarySuspension: Boolean,
  totalCredits: Number,
  takenCourses: String,
  currentPracticesCredits: Number,
  approvedPracticesCredits: Number,
  currentRequiredCredits: Number,
  approvedRequiredCredits: Number,
  currentEssencialCredits: Number,
  approvedEssencialCredits: Number,
  currentElectiveCredits: Number,
  approvedElectiveCredits: Number,
  currentElectiveHmCredits: Number,
  approvedElectiveHmCredits: Number,
  currentCompCredits: Number,
  approvedCompCredits: Number,
  avgTakenCredits: Number,
  avgApprovedCredits: Number,
  totalRequiredCredits: Number,
  currentCredits: Number,
  lastUpdateInfo: Date,
  dateCreation: { type: Date, required: true },
  userCreator: { type: String, required: true },
  dateUpdate: Date,
  userUpdater: String,
}, { timestamps: true });
schema.index({ enrolledProgramId: 1 });
export default mongoose.model("ProfileProgramExtraInfo", schema, "profile_program_extra_info");
